/*Copyright (c) 2020-2021 aio.co.id All Rights Reserved.
 This software is the confidential and proprietary information of aio.co.id You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with aio.co.id*/
package id.co.aio.procure_to_pay.avm2;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * BankData generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`BankData`")
@IdClass(BankDataId.class)
public class BankData implements Serializable {

    private String mandt;
    private String lifnr;
    private String banks;
    private String bankl;
    private String bankn;
    private String f6;
    private Double bkont;
    private String bvtyp;
    private String xezer;
    private Double bkref;
    private String koinh;
    private String ebppAccname;
    private String ebppBvstatus;
    private LocalDateTime kovon;
    private LocalDateTime kobis;

    @Id
    @Column(name = "`MANDT`", nullable = true, length = 255)
    public String getMandt() {
        return this.mandt;
    }

    public void setMandt(String mandt) {
        this.mandt = mandt;
    }

    @Id
    @Column(name = "`LIFNR`", nullable = true, length = 255)
    public String getLifnr() {
        return this.lifnr;
    }

    public void setLifnr(String lifnr) {
        this.lifnr = lifnr;
    }

    @Column(name = "`BANKS`", nullable = true, length = 255)
    public String getBanks() {
        return this.banks;
    }

    public void setBanks(String banks) {
        this.banks = banks;
    }

    @Column(name = "`BANKL`", nullable = true, length = 255)
    public String getBankl() {
        return this.bankl;
    }

    public void setBankl(String bankl) {
        this.bankl = bankl;
    }

    @Column(name = "`BANKN`", nullable = true, length = 255)
    public String getBankn() {
        return this.bankn;
    }

    public void setBankn(String bankn) {
        this.bankn = bankn;
    }

    @Column(name = "`F6`", nullable = true, length = 255)
    public String getF6() {
        return this.f6;
    }

    public void setF6(String f6) {
        this.f6 = f6;
    }

    @Column(name = "`BKONT`", nullable = true, scale = 9, precision = 15)
    public Double getBkont() {
        return this.bkont;
    }

    public void setBkont(Double bkont) {
        this.bkont = bkont;
    }

    @Column(name = "`BVTYP`", nullable = true, length = 255)
    public String getBvtyp() {
        return this.bvtyp;
    }

    public void setBvtyp(String bvtyp) {
        this.bvtyp = bvtyp;
    }

    @Column(name = "`XEZER`", nullable = true, length = 255)
    public String getXezer() {
        return this.xezer;
    }

    public void setXezer(String xezer) {
        this.xezer = xezer;
    }

    @Column(name = "`BKREF`", nullable = true, scale = 9, precision = 15)
    public Double getBkref() {
        return this.bkref;
    }

    public void setBkref(Double bkref) {
        this.bkref = bkref;
    }

    @Column(name = "`KOINH`", nullable = true, length = 255)
    public String getKoinh() {
        return this.koinh;
    }

    public void setKoinh(String koinh) {
        this.koinh = koinh;
    }

    @Column(name = "`EBPP_ACCNAME`", nullable = true, length = 255)
    public String getEbppAccname() {
        return this.ebppAccname;
    }

    public void setEbppAccname(String ebppAccname) {
        this.ebppAccname = ebppAccname;
    }

    @Column(name = "`EBPP_BVSTATUS`", nullable = true, length = 255)
    public String getEbppBvstatus() {
        return this.ebppBvstatus;
    }

    public void setEbppBvstatus(String ebppBvstatus) {
        this.ebppBvstatus = ebppBvstatus;
    }

    @Column(name = "`KOVON`", nullable = true)
    public LocalDateTime getKovon() {
        return this.kovon;
    }

    public void setKovon(LocalDateTime kovon) {
        this.kovon = kovon;
    }

    @Column(name = "`KOBIS`", nullable = true)
    public LocalDateTime getKobis() {
        return this.kobis;
    }

    public void setKobis(LocalDateTime kobis) {
        this.kobis = kobis;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof BankData)) return false;
        final BankData bankData = (BankData) o;
        return Objects.equals(getMandt(), bankData.getMandt()) &&
                Objects.equals(getLifnr(), bankData.getLifnr());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getMandt(),
                getLifnr());
    }
}