/*Copyright (c) 2020-2021 aio.co.id All Rights Reserved.
 This software is the confidential and proprietary information of aio.co.id You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with aio.co.id*/
package id.co.aio.procure_to_pay.avm2;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

public class CategoryVendorId implements Serializable {

    private Double abIdry;
    private String abIdryve;
    private Double abIdor;

    public Double getAbIdry() {
        return this.abIdry;
    }

    public void setAbIdry(Double abIdry) {
        this.abIdry = abIdry;
    }

    public String getAbIdryve() {
        return this.abIdryve;
    }

    public void setAbIdryve(String abIdryve) {
        this.abIdryve = abIdryve;
    }

    public Double getAbIdor() {
        return this.abIdor;
    }

    public void setAbIdor(Double abIdor) {
        this.abIdor = abIdor;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof CategoryVendor)) return false;
        final CategoryVendor categoryVendor = (CategoryVendor) o;
        return Objects.equals(getAbIdry(), categoryVendor.getAbIdry()) &&
                Objects.equals(getAbIdryve(), categoryVendor.getAbIdryve()) &&
                Objects.equals(getAbIdor(), categoryVendor.getAbIdor());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getAbIdry(),
                getAbIdryve(),
                getAbIdor());
    }
}