/*Copyright (c) 2020-2021 aio.co.id All Rights Reserved.
 This software is the confidential and proprietary information of aio.co.id You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with aio.co.id*/
package id.co.aio.procure_to_pay.avm2;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TlMsAgpe generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`tl_ms_agpe`")
public class TlMsAgpe implements Serializable {

    private Integer abIdagpe;
    private String abAgpe;

    @Id
    @Column(name = "`ab_idagpe`", nullable = false, scale = 0, precision = 10)
    public Integer getAbIdagpe() {
        return this.abIdagpe;
    }

    public void setAbIdagpe(Integer abIdagpe) {
        this.abIdagpe = abIdagpe;
    }

    @Column(name = "`ab_agpe`", nullable = false, length = 200)
    public String getAbAgpe() {
        return this.abAgpe;
    }

    public void setAbAgpe(String abAgpe) {
        this.abAgpe = abAgpe;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TlMsAgpe)) return false;
        final TlMsAgpe tlMsAgpe = (TlMsAgpe) o;
        return Objects.equals(getAbIdagpe(), tlMsAgpe.getAbIdagpe());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getAbIdagpe());
    }
}