/*Copyright (c) 2020-2021 aio.co.id All Rights Reserved.
 This software is the confidential and proprietary information of aio.co.id You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with aio.co.id*/
package id.co.aio.procure_to_pay.avm2;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TlMsForgotUser generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`tl_ms_forgot_user`")
public class TlMsForgotUser implements Serializable {

    private Integer abId;
    private String abUsername;
    private String abCompanyName;
    private String abCompanyNpwp;
    private String abCompanyEmail;
    private String abKtp;
    private String abStatus;
    private String abPuon;
    private LocalDateTime abApprovalDate;
    private LocalDateTime abCreatedDate;

    @Id
    @Column(name = "`ab_id`", nullable = false, scale = 0, precision = 10)
    public Integer getAbId() {
        return this.abId;
    }

    public void setAbId(Integer abId) {
        this.abId = abId;
    }

    @Column(name = "`ab_username`", nullable = true, length = 55)
    public String getAbUsername() {
        return this.abUsername;
    }

    public void setAbUsername(String abUsername) {
        this.abUsername = abUsername;
    }

    @Column(name = "`ab_company_name`", nullable = true, length = 55)
    public String getAbCompanyName() {
        return this.abCompanyName;
    }

    public void setAbCompanyName(String abCompanyName) {
        this.abCompanyName = abCompanyName;
    }

    @Column(name = "`ab_company_npwp`", nullable = true, length = 55)
    public String getAbCompanyNpwp() {
        return this.abCompanyNpwp;
    }

    public void setAbCompanyNpwp(String abCompanyNpwp) {
        this.abCompanyNpwp = abCompanyNpwp;
    }

    @Column(name = "`ab_company_email`", nullable = true, length = 55)
    public String getAbCompanyEmail() {
        return this.abCompanyEmail;
    }

    public void setAbCompanyEmail(String abCompanyEmail) {
        this.abCompanyEmail = abCompanyEmail;
    }

    @Column(name = "`ab_ktp`", nullable = true, length = 25)
    public String getAbKtp() {
        return this.abKtp;
    }

    public void setAbKtp(String abKtp) {
        this.abKtp = abKtp;
    }

    @Column(name = "`ab_status`", nullable = true, length = 15)
    public String getAbStatus() {
        return this.abStatus;
    }

    public void setAbStatus(String abStatus) {
        this.abStatus = abStatus;
    }

    @Column(name = "`ab_puon`", nullable = true, length = 5)
    public String getAbPuon() {
        return this.abPuon;
    }

    public void setAbPuon(String abPuon) {
        this.abPuon = abPuon;
    }

    @Column(name = "`ab_approval_date`", nullable = true)
    public LocalDateTime getAbApprovalDate() {
        return this.abApprovalDate;
    }

    public void setAbApprovalDate(LocalDateTime abApprovalDate) {
        this.abApprovalDate = abApprovalDate;
    }

    @Column(name = "`ab_created_date`", nullable = true)
    public LocalDateTime getAbCreatedDate() {
        return this.abCreatedDate;
    }

    public void setAbCreatedDate(LocalDateTime abCreatedDate) {
        this.abCreatedDate = abCreatedDate;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TlMsForgotUser)) return false;
        final TlMsForgotUser tlMsForgotUser = (TlMsForgotUser) o;
        return Objects.equals(getAbId(), tlMsForgotUser.getAbId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getAbId());
    }
}