/*Copyright (c) 2020-2021 aio.co.id All Rights Reserved.
 This software is the confidential and proprietary information of aio.co.id You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with aio.co.id*/
package id.co.aio.procure_to_pay.aio_ptp;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblMPurchaseGroup generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`tbl_m_purchase_group`")
public class TblMPurchaseGroup implements Serializable {

    private Integer id;
    private String purchaseGroupId;
    private String purchaseGroup;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`id`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`purchase_group_id`", nullable = true, length = 20)
    public String getPurchaseGroupId() {
        return this.purchaseGroupId;
    }

    public void setPurchaseGroupId(String purchaseGroupId) {
        this.purchaseGroupId = purchaseGroupId;
    }

    @Column(name = "`purchase_group`", nullable = true, length = 100)
    public String getPurchaseGroup() {
        return this.purchaseGroup;
    }

    public void setPurchaseGroup(String purchaseGroup) {
        this.purchaseGroup = purchaseGroup;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TblMPurchaseGroup)) return false;
        final TblMPurchaseGroup tblMpurchaseGroup = (TblMPurchaseGroup) o;
        return Objects.equals(getId(), tblMpurchaseGroup.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}