/*Copyright (c) 2020-2021 aio.co.id All Rights Reserved.
 This software is the confidential and proprietary information of aio.co.id You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with aio.co.id*/
package id.co.aio.procure_to_pay.aio_ptp;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * TblTBudgetDetails generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`tbl_t_budget_details`")
public class TblTBudgetDetails implements Serializable {

    private Integer bdId;
    private Integer rcatId;
    private Integer ubCatId;
    private Integer bhId;
    private BigDecimal bdOriginal;
    private String bdDocumentId;
    private String bdAdjustmentType;
    private BigDecimal bdAfterAdjustment;
    private String bdStatus = "active";
    private String bdCreatedBy = "SYSTEM";
    private LocalDateTime bdCreatedAt;
    private String bdRemarks;
    private String coaId;
    private BigDecimal bdAdjustment;
    private Integer bdAdditionalDocId;
    private String bdAdditionalDocType;
    private BigDecimal prActual;
    private BigDecimal poActual;
    private Integer buId;
    private TblMReclassCategory tblMreclassCategory;
    private TblMUnbudgetCat tblMunbudgetCat;
    private TblTBudgetHeader tblTbudgetHeader;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`bd_id`", nullable = false, scale = 0, precision = 10)
    public Integer getBdId() {
        return this.bdId;
    }

    public void setBdId(Integer bdId) {
        this.bdId = bdId;
    }

    @Column(name = "`r_cat_id`", nullable = true, scale = 0, precision = 10)
    public Integer getRcatId() {
        return this.rcatId;
    }

    public void setRcatId(Integer rcatId) {
        this.rcatId = rcatId;
    }

    @Column(name = "`ub_cat_id`", nullable = true, scale = 0, precision = 10)
    public Integer getUbCatId() {
        return this.ubCatId;
    }

    public void setUbCatId(Integer ubCatId) {
        this.ubCatId = ubCatId;
    }

    @Column(name = "`bh_id`", nullable = true, scale = 0, precision = 10)
    public Integer getBhId() {
        return this.bhId;
    }

    public void setBhId(Integer bhId) {
        this.bhId = bhId;
    }

    @Column(name = "`bd_original`", nullable = true, scale = 3, precision = 30)
    public BigDecimal getBdOriginal() {
        return this.bdOriginal;
    }

    public void setBdOriginal(BigDecimal bdOriginal) {
        this.bdOriginal = bdOriginal;
    }

    @Column(name = "`bd_document_id`", nullable = true, length = 100)
    public String getBdDocumentId() {
        return this.bdDocumentId;
    }

    public void setBdDocumentId(String bdDocumentId) {
        this.bdDocumentId = bdDocumentId;
    }

    @Column(name = "`bd_adjustment_type`", nullable = true, length = 100)
    public String getBdAdjustmentType() {
        return this.bdAdjustmentType;
    }

    public void setBdAdjustmentType(String bdAdjustmentType) {
        this.bdAdjustmentType = bdAdjustmentType;
    }

    @Column(name = "`bd_after_adjustment`", nullable = true, scale = 3, precision = 30)
    public BigDecimal getBdAfterAdjustment() {
        return this.bdAfterAdjustment;
    }

    public void setBdAfterAdjustment(BigDecimal bdAfterAdjustment) {
        this.bdAfterAdjustment = bdAfterAdjustment;
    }

    @Column(name = "`bd_status`", nullable = true, length = 20)
    public String getBdStatus() {
        return this.bdStatus;
    }

    public void setBdStatus(String bdStatus) {
        this.bdStatus = bdStatus;
    }

    @Column(name = "`bd_created_by`", nullable = true, length = 100)
    public String getBdCreatedBy() {
        return this.bdCreatedBy;
    }

    public void setBdCreatedBy(String bdCreatedBy) {
        this.bdCreatedBy = bdCreatedBy;
    }

    @Column(name = "`bd_created_at`", nullable = true)
    public LocalDateTime getBdCreatedAt() {
        return this.bdCreatedAt;
    }

    public void setBdCreatedAt(LocalDateTime bdCreatedAt) {
        this.bdCreatedAt = bdCreatedAt;
    }

    @Column(name = "`bd_remarks`", nullable = true, length = 65535)
    public String getBdRemarks() {
        return this.bdRemarks;
    }

    public void setBdRemarks(String bdRemarks) {
        this.bdRemarks = bdRemarks;
    }

    @Column(name = "`coa_id`", nullable = true, length = 100)
    public String getCoaId() {
        return this.coaId;
    }

    public void setCoaId(String coaId) {
        this.coaId = coaId;
    }

    @Column(name = "`bd_adjustment`", nullable = true, scale = 3, precision = 30)
    public BigDecimal getBdAdjustment() {
        return this.bdAdjustment;
    }

    public void setBdAdjustment(BigDecimal bdAdjustment) {
        this.bdAdjustment = bdAdjustment;
    }

    @Column(name = "`bd_additional_doc_id`", nullable = true, scale = 0, precision = 10)
    public Integer getBdAdditionalDocId() {
        return this.bdAdditionalDocId;
    }

    public void setBdAdditionalDocId(Integer bdAdditionalDocId) {
        this.bdAdditionalDocId = bdAdditionalDocId;
    }

    @Column(name = "`bd_additional_doc_type`", nullable = true, length = 100)
    public String getBdAdditionalDocType() {
        return this.bdAdditionalDocType;
    }

    public void setBdAdditionalDocType(String bdAdditionalDocType) {
        this.bdAdditionalDocType = bdAdditionalDocType;
    }

    @Column(name = "`pr_actual`", nullable = true, scale = 3, precision = 30)
    public BigDecimal getPrActual() {
        return this.prActual;
    }

    public void setPrActual(BigDecimal prActual) {
        this.prActual = prActual;
    }

    @Column(name = "`po_actual`", nullable = true, scale = 3, precision = 30)
    public BigDecimal getPoActual() {
        return this.poActual;
    }

    public void setPoActual(BigDecimal poActual) {
        this.poActual = poActual;
    }

    @Column(name = "`bu_id`", nullable = true, scale = 0, precision = 10)
    public Integer getBuId() {
        return this.buId;
    }

    public void setBuId(Integer buId) {
        this.buId = buId;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`r_cat_id`", referencedColumnName = "`r_cat_id`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`tbl_t_budget_details_ibfk_1`"))
    @Fetch(FetchMode.JOIN)
    public TblMReclassCategory getTblMreclassCategory() {
        return this.tblMreclassCategory;
    }

    public void setTblMreclassCategory(TblMReclassCategory tblMreclassCategory) {
        if(tblMreclassCategory != null) {
            this.rcatId = tblMreclassCategory.getRcatId();
        }

        this.tblMreclassCategory = tblMreclassCategory;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`ub_cat_id`", referencedColumnName = "`ub_cat_id`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`tbl_t_budget_details_ibfk_2`"))
    @Fetch(FetchMode.JOIN)
    public TblMUnbudgetCat getTblMunbudgetCat() {
        return this.tblMunbudgetCat;
    }

    public void setTblMunbudgetCat(TblMUnbudgetCat tblMunbudgetCat) {
        if(tblMunbudgetCat != null) {
            this.ubCatId = tblMunbudgetCat.getUbCatId();
        }

        this.tblMunbudgetCat = tblMunbudgetCat;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`bh_id`", referencedColumnName = "`bh_id`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`tbl_t_budget_details_ibfk_3`"))
    @Fetch(FetchMode.JOIN)
    public TblTBudgetHeader getTblTbudgetHeader() {
        return this.tblTbudgetHeader;
    }

    public void setTblTbudgetHeader(TblTBudgetHeader tblTbudgetHeader) {
        if(tblTbudgetHeader != null) {
            this.bhId = tblTbudgetHeader.getBhId();
        }

        this.tblTbudgetHeader = tblTbudgetHeader;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TblTBudgetDetails)) return false;
        final TblTBudgetDetails tblTbudgetDetails = (TblTBudgetDetails) o;
        return Objects.equals(getBdId(), tblTbudgetDetails.getBdId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getBdId());
    }
}