/*Copyright (c) 2020-2021 aio.co.id All Rights Reserved.
 This software is the confidential and proprietary information of aio.co.id You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with aio.co.id*/
package id.co.aio.procure_to_pay.aio_ptp;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblTPoLineItem generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`tbl_t_po_line_item`")
public class TblTPoLineItem implements Serializable {

    private Integer id;
    private Integer idPoHeader;
    private Integer idPrHeader;
    private Integer idPrLineItemHeader;
    private String item;
    private BigDecimal poQty;
    private String uom;
    private Double unitPrice;
    private Double itemAmountAfterDiscount;
    private BigDecimal itemTotalAmount;
    private String matlGroup;
    private String matlGroupDesc;
    private String plant;
    private LocalDateTime eta;
    private String ioNumber;
    private String costCenter;
    private String coa;
    private String assetsNo;
    private String prNo;
    private String prNoItem;
    private String sapPrNo;
    private BigDecimal discount;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`id`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`id_po_header`", nullable = true, scale = 0, precision = 10)
    public Integer getIdPoHeader() {
        return this.idPoHeader;
    }

    public void setIdPoHeader(Integer idPoHeader) {
        this.idPoHeader = idPoHeader;
    }

    @Column(name = "`id_pr_header`", nullable = true, scale = 0, precision = 10)
    public Integer getIdPrHeader() {
        return this.idPrHeader;
    }

    public void setIdPrHeader(Integer idPrHeader) {
        this.idPrHeader = idPrHeader;
    }

    @Column(name = "`id_pr_line_item_header`", nullable = true, scale = 0, precision = 10)
    public Integer getIdPrLineItemHeader() {
        return this.idPrLineItemHeader;
    }

    public void setIdPrLineItemHeader(Integer idPrLineItemHeader) {
        this.idPrLineItemHeader = idPrLineItemHeader;
    }

    @Column(name = "`item`", nullable = true, length = 255)
    public String getItem() {
        return this.item;
    }

    public void setItem(String item) {
        this.item = item;
    }

    @Column(name = "`po_qty`", nullable = true, scale = 9, precision = 20)
    public BigDecimal getPoQty() {
        return this.poQty;
    }

    public void setPoQty(BigDecimal poQty) {
        this.poQty = poQty;
    }

    @Column(name = "`uom`", nullable = true, length = 255)
    public String getUom() {
        return this.uom;
    }

    public void setUom(String uom) {
        this.uom = uom;
    }

    @Column(name = "`unit_price`", nullable = true, scale = 2, precision = 30)
    public Double getUnitPrice() {
        return this.unitPrice;
    }

    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }

    @Column(name = "`item_amount_after_discount`", nullable = true, scale = 2, precision = 30)
    public Double getItemAmountAfterDiscount() {
        return this.itemAmountAfterDiscount;
    }

    public void setItemAmountAfterDiscount(Double itemAmountAfterDiscount) {
        this.itemAmountAfterDiscount = itemAmountAfterDiscount;
    }

    @Column(name = "`item_total_amount`", nullable = true, scale = 2, precision = 30)
    public BigDecimal getItemTotalAmount() {
        return this.itemTotalAmount;
    }

    public void setItemTotalAmount(BigDecimal itemTotalAmount) {
        this.itemTotalAmount = itemTotalAmount;
    }

    @Column(name = "`matl_group`", nullable = true, length = 255)
    public String getMatlGroup() {
        return this.matlGroup;
    }

    public void setMatlGroup(String matlGroup) {
        this.matlGroup = matlGroup;
    }

    @Column(name = "`matl_group_desc`", nullable = true, length = 255)
    public String getMatlGroupDesc() {
        return this.matlGroupDesc;
    }

    public void setMatlGroupDesc(String matlGroupDesc) {
        this.matlGroupDesc = matlGroupDesc;
    }

    @Column(name = "`plant`", nullable = true, length = 255)
    public String getPlant() {
        return this.plant;
    }

    public void setPlant(String plant) {
        this.plant = plant;
    }

    @Column(name = "`eta`", nullable = true)
    public LocalDateTime getEta() {
        return this.eta;
    }

    public void setEta(LocalDateTime eta) {
        this.eta = eta;
    }

    @Column(name = "`io_number`", nullable = true, length = 30)
    public String getIoNumber() {
        return this.ioNumber;
    }

    public void setIoNumber(String ioNumber) {
        this.ioNumber = ioNumber;
    }

    @Column(name = "`cost_center`", nullable = true, length = 255)
    public String getCostCenter() {
        return this.costCenter;
    }

    public void setCostCenter(String costCenter) {
        this.costCenter = costCenter;
    }

    @Column(name = "`coa`", nullable = true, length = 255)
    public String getCoa() {
        return this.coa;
    }

    public void setCoa(String coa) {
        this.coa = coa;
    }

    @Column(name = "`assets_no`", nullable = true, length = 30)
    public String getAssetsNo() {
        return this.assetsNo;
    }

    public void setAssetsNo(String assetsNo) {
        this.assetsNo = assetsNo;
    }

    @Column(name = "`pr_no`", nullable = true, length = 30)
    public String getPrNo() {
        return this.prNo;
    }

    public void setPrNo(String prNo) {
        this.prNo = prNo;
    }

    @Column(name = "`pr_no_item`", nullable = true, length = 255)
    public String getPrNoItem() {
        return this.prNoItem;
    }

    public void setPrNoItem(String prNoItem) {
        this.prNoItem = prNoItem;
    }

    @Column(name = "`sap_pr_no`", nullable = true, length = 50)
    public String getSapPrNo() {
        return this.sapPrNo;
    }

    public void setSapPrNo(String sapPrNo) {
        this.sapPrNo = sapPrNo;
    }

    @Column(name = "`discount`", nullable = true, scale = 2, precision = 65)
    public BigDecimal getDiscount() {
        return this.discount;
    }

    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TblTPoLineItem)) return false;
        final TblTPoLineItem tblTpoLineItem = (TblTPoLineItem) o;
        return Objects.equals(getId(), tblTpoLineItem.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}