/*Copyright (c) 2020-2021 aio.co.id All Rights Reserved.
 This software is the confidential and proprietary information of aio.co.id You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with aio.co.id*/
package id.co.aio.procure_to_pay.aio_ptp;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblTPoAcceptanceVendor generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`tbl_t_po_acceptance_vendor`")
public class TblTPoAcceptanceVendor implements Serializable {

    private Integer id;
    private String idPo;
    private String name;
    private String position;
    private LocalDateTime acceptedAt;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`id`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`id_po`", nullable = true, length = 255)
    public String getIdPo() {
        return this.idPo;
    }

    public void setIdPo(String idPo) {
        this.idPo = idPo;
    }

    @Column(name = "`name`", nullable = true, length = 255)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "`position`", nullable = true, length = 255)
    public String getPosition() {
        return this.position;
    }

    public void setPosition(String position) {
        this.position = position;
    }

    @Column(name = "`accepted_at`", nullable = true)
    public LocalDateTime getAcceptedAt() {
        return this.acceptedAt;
    }

    public void setAcceptedAt(LocalDateTime acceptedAt) {
        this.acceptedAt = acceptedAt;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TblTPoAcceptanceVendor)) return false;
        final TblTPoAcceptanceVendor tblTpoAcceptanceVendor = (TblTPoAcceptanceVendor) o;
        return Objects.equals(getId(), tblTpoAcceptanceVendor.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}