/*Copyright (c) 2020-2021 aio.co.id All Rights Reserved.
 This software is the confidential and proprietary information of aio.co.id You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with aio.co.id*/
package id.co.aio.procure_to_pay.aio_ptp.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class SpBudgetDetailsResponseContent implements Serializable {


    @ColumnAlias("actual")
    private BigDecimal actual;

    @ColumnAlias("additional")
    private BigDecimal additional;

    @ColumnAlias("adjustment")
    private BigDecimal adjustment;

    @ColumnAlias("available")
    private BigDecimal available;

    @ColumnAlias("bd_id")
    private Integer bdId;

    @ColumnAlias("bh_id")
    private Integer bhId;

    @ColumnAlias("budget_after_adjustment")
    private BigDecimal budgetAfterAdjustment;

    @ColumnAlias("budget_original")
    private BigDecimal budgetOriginal;

    @ColumnAlias("coa")
    private String coa;

    @ColumnAlias("commitment")
    private BigDecimal commitment;

    @ColumnAlias("created_by")
    private String createdBy;

    @ColumnAlias("creator")
    private String creator;

    @ColumnAlias("datetime")
    private LocalDateTime datetime;

    @ColumnAlias("doc_number")
    private String docNumber;

    @ColumnAlias("io")
    private String io;

    @ColumnAlias("reclass")
    private BigDecimal reclass;

    @ColumnAlias("remarks")
    private String remarks;

    @ColumnAlias("reserved")
    private BigDecimal reserved;

    @ColumnAlias("type")
    private String type;

    @ColumnAlias("year")
    private String year;

    @ColumnAlias("bd_additional_doc_id")
    private Integer bdAdditionalDocId;

    @ColumnAlias("bd_additional_doc_type")
    private String bdAdditionalDocType;

    public BigDecimal getActual() {
        return this.actual;
    }

    public void setActual(BigDecimal actual) {
        this.actual = actual;
    }

    public BigDecimal getAdditional() {
        return this.additional;
    }

    public void setAdditional(BigDecimal additional) {
        this.additional = additional;
    }

    public BigDecimal getAdjustment() {
        return this.adjustment;
    }

    public void setAdjustment(BigDecimal adjustment) {
        this.adjustment = adjustment;
    }

    public BigDecimal getAvailable() {
        return this.available;
    }

    public void setAvailable(BigDecimal available) {
        this.available = available;
    }

    public Integer getBdId() {
        return this.bdId;
    }

    public void setBdId(Integer bdId) {
        this.bdId = bdId;
    }

    public Integer getBhId() {
        return this.bhId;
    }

    public void setBhId(Integer bhId) {
        this.bhId = bhId;
    }

    public BigDecimal getBudgetAfterAdjustment() {
        return this.budgetAfterAdjustment;
    }

    public void setBudgetAfterAdjustment(BigDecimal budgetAfterAdjustment) {
        this.budgetAfterAdjustment = budgetAfterAdjustment;
    }

    public BigDecimal getBudgetOriginal() {
        return this.budgetOriginal;
    }

    public void setBudgetOriginal(BigDecimal budgetOriginal) {
        this.budgetOriginal = budgetOriginal;
    }

    public String getCoa() {
        return this.coa;
    }

    public void setCoa(String coa) {
        this.coa = coa;
    }

    public BigDecimal getCommitment() {
        return this.commitment;
    }

    public void setCommitment(BigDecimal commitment) {
        this.commitment = commitment;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public String getCreator() {
        return this.creator;
    }

    public void setCreator(String creator) {
        this.creator = creator;
    }

    public LocalDateTime getDatetime() {
        return this.datetime;
    }

    public void setDatetime(LocalDateTime datetime) {
        this.datetime = datetime;
    }

    public String getDocNumber() {
        return this.docNumber;
    }

    public void setDocNumber(String docNumber) {
        this.docNumber = docNumber;
    }

    public String getIo() {
        return this.io;
    }

    public void setIo(String io) {
        this.io = io;
    }

    public BigDecimal getReclass() {
        return this.reclass;
    }

    public void setReclass(BigDecimal reclass) {
        this.reclass = reclass;
    }

    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public BigDecimal getReserved() {
        return this.reserved;
    }

    public void setReserved(BigDecimal reserved) {
        this.reserved = reserved;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getYear() {
        return this.year;
    }

    public void setYear(String year) {
        this.year = year;
    }

    public Integer getBdAdditionalDocId() {
        return this.bdAdditionalDocId;
    }

    public void setBdAdditionalDocId(Integer bdAdditionalDocId) {
        this.bdAdditionalDocId = bdAdditionalDocId;
    }

    public String getBdAdditionalDocType() {
        return this.bdAdditionalDocType;
    }

    public void setBdAdditionalDocType(String bdAdditionalDocType) {
        this.bdAdditionalDocType = bdAdditionalDocType;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SpBudgetDetailsResponseContent)) return false;
        final SpBudgetDetailsResponseContent spBudgetDetailsResponseContent = (SpBudgetDetailsResponseContent) o;
        return Objects.equals(getActual(), spBudgetDetailsResponseContent.getActual()) &&
                Objects.equals(getAdditional(), spBudgetDetailsResponseContent.getAdditional()) &&
                Objects.equals(getAdjustment(), spBudgetDetailsResponseContent.getAdjustment()) &&
                Objects.equals(getAvailable(), spBudgetDetailsResponseContent.getAvailable()) &&
                Objects.equals(getBdId(), spBudgetDetailsResponseContent.getBdId()) &&
                Objects.equals(getBhId(), spBudgetDetailsResponseContent.getBhId()) &&
                Objects.equals(getBudgetAfterAdjustment(), spBudgetDetailsResponseContent.getBudgetAfterAdjustment()) &&
                Objects.equals(getBudgetOriginal(), spBudgetDetailsResponseContent.getBudgetOriginal()) &&
                Objects.equals(getCoa(), spBudgetDetailsResponseContent.getCoa()) &&
                Objects.equals(getCommitment(), spBudgetDetailsResponseContent.getCommitment()) &&
                Objects.equals(getCreatedBy(), spBudgetDetailsResponseContent.getCreatedBy()) &&
                Objects.equals(getCreator(), spBudgetDetailsResponseContent.getCreator()) &&
                Objects.equals(getDatetime(), spBudgetDetailsResponseContent.getDatetime()) &&
                Objects.equals(getDocNumber(), spBudgetDetailsResponseContent.getDocNumber()) &&
                Objects.equals(getIo(), spBudgetDetailsResponseContent.getIo()) &&
                Objects.equals(getReclass(), spBudgetDetailsResponseContent.getReclass()) &&
                Objects.equals(getRemarks(), spBudgetDetailsResponseContent.getRemarks()) &&
                Objects.equals(getReserved(), spBudgetDetailsResponseContent.getReserved()) &&
                Objects.equals(getType(), spBudgetDetailsResponseContent.getType()) &&
                Objects.equals(getYear(), spBudgetDetailsResponseContent.getYear()) &&
                Objects.equals(getBdAdditionalDocId(), spBudgetDetailsResponseContent.getBdAdditionalDocId()) &&
                Objects.equals(getBdAdditionalDocType(), spBudgetDetailsResponseContent.getBdAdditionalDocType());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getActual(),
                getAdditional(),
                getAdjustment(),
                getAvailable(),
                getBdId(),
                getBhId(),
                getBudgetAfterAdjustment(),
                getBudgetOriginal(),
                getCoa(),
                getCommitment(),
                getCreatedBy(),
                getCreator(),
                getDatetime(),
                getDocNumber(),
                getIo(),
                getReclass(),
                getRemarks(),
                getReserved(),
                getType(),
                getYear(),
                getBdAdditionalDocId(),
                getBdAdditionalDocType());
    }
}