/*Copyright (c) 2020-2021 aio.co.id All Rights Reserved.
 This software is the confidential and proprietary information of aio.co.id You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with aio.co.id*/
package id.co.aio.procure_to_pay.avm2.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetDataVendorByCodeResponse implements Serializable {


    @ColumnAlias("address")
    private String address;

    @ColumnAlias("VendorCode")
    private String vendorCode;

    @ColumnAlias("VendorName")
    private String vendorName;

    @ColumnAlias("Email")
    private String email;

    @ColumnAlias("ADD1")
    private String add1;

    @ColumnAlias("ADD2")
    private String add2;

    @ColumnAlias("ADD3")
    private String add3;

    @ColumnAlias("City")
    private String city;

    @ColumnAlias("GroupVendor")
    private String groupVendor;

    @ColumnAlias("Title")
    private String title;

    @ColumnAlias("npwp")
    private String npwp;

    @ColumnAlias("Region")
    private String region;

    @ColumnAlias("Country")
    private String country;

    @ColumnAlias("Email1")
    private String email1;

    @ColumnAlias("Email2")
    private String email2;

    @ColumnAlias("Telephone")
    private String telephone;

    @ColumnAlias("MobilePhone")
    private String mobilePhone;

    @ColumnAlias("DirectorName")
    private String directorName;

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getVendorCode() {
        return this.vendorCode;
    }

    public void setVendorCode(String vendorCode) {
        this.vendorCode = vendorCode;
    }

    public String getVendorName() {
        return this.vendorName;
    }

    public void setVendorName(String vendorName) {
        this.vendorName = vendorName;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getAdd1() {
        return this.add1;
    }

    public void setAdd1(String add1) {
        this.add1 = add1;
    }

    public String getAdd2() {
        return this.add2;
    }

    public void setAdd2(String add2) {
        this.add2 = add2;
    }

    public String getAdd3() {
        return this.add3;
    }

    public void setAdd3(String add3) {
        this.add3 = add3;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getGroupVendor() {
        return this.groupVendor;
    }

    public void setGroupVendor(String groupVendor) {
        this.groupVendor = groupVendor;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getNpwp() {
        return this.npwp;
    }

    public void setNpwp(String npwp) {
        this.npwp = npwp;
    }

    public String getRegion() {
        return this.region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getEmail1() {
        return this.email1;
    }

    public void setEmail1(String email1) {
        this.email1 = email1;
    }

    public String getEmail2() {
        return this.email2;
    }

    public void setEmail2(String email2) {
        this.email2 = email2;
    }

    public String getTelephone() {
        return this.telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public String getMobilePhone() {
        return this.mobilePhone;
    }

    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }

    public String getDirectorName() {
        return this.directorName;
    }

    public void setDirectorName(String directorName) {
        this.directorName = directorName;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetDataVendorByCodeResponse)) return false;
        final GetDataVendorByCodeResponse getDataVendorByCodeResponse = (GetDataVendorByCodeResponse) o;
        return Objects.equals(getAddress(), getDataVendorByCodeResponse.getAddress()) &&
                Objects.equals(getVendorCode(), getDataVendorByCodeResponse.getVendorCode()) &&
                Objects.equals(getVendorName(), getDataVendorByCodeResponse.getVendorName()) &&
                Objects.equals(getEmail(), getDataVendorByCodeResponse.getEmail()) &&
                Objects.equals(getAdd1(), getDataVendorByCodeResponse.getAdd1()) &&
                Objects.equals(getAdd2(), getDataVendorByCodeResponse.getAdd2()) &&
                Objects.equals(getAdd3(), getDataVendorByCodeResponse.getAdd3()) &&
                Objects.equals(getCity(), getDataVendorByCodeResponse.getCity()) &&
                Objects.equals(getGroupVendor(), getDataVendorByCodeResponse.getGroupVendor()) &&
                Objects.equals(getTitle(), getDataVendorByCodeResponse.getTitle()) &&
                Objects.equals(getNpwp(), getDataVendorByCodeResponse.getNpwp()) &&
                Objects.equals(getRegion(), getDataVendorByCodeResponse.getRegion()) &&
                Objects.equals(getCountry(), getDataVendorByCodeResponse.getCountry()) &&
                Objects.equals(getEmail1(), getDataVendorByCodeResponse.getEmail1()) &&
                Objects.equals(getEmail2(), getDataVendorByCodeResponse.getEmail2()) &&
                Objects.equals(getTelephone(), getDataVendorByCodeResponse.getTelephone()) &&
                Objects.equals(getMobilePhone(), getDataVendorByCodeResponse.getMobilePhone()) &&
                Objects.equals(getDirectorName(), getDataVendorByCodeResponse.getDirectorName());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getAddress(),
                getVendorCode(),
                getVendorName(),
                getEmail(),
                getAdd1(),
                getAdd2(),
                getAdd3(),
                getCity(),
                getGroupVendor(),
                getTitle(),
                getNpwp(),
                getRegion(),
                getCountry(),
                getEmail1(),
                getEmail2(),
                getTelephone(),
                getMobilePhone(),
                getDirectorName());
    }
}