/*Copyright (c) 2020-2021 aio.co.id All Rights Reserved.
 This software is the confidential and proprietary information of aio.co.id You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with aio.co.id*/
package id.co.aio.procure_to_pay.avm2.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetPicResponse implements Serializable {


    @ColumnAlias("ab_idil")
    private Integer abIdil;

    @ColumnAlias("ab_coorsa")
    private String abCoorsa;

    @ColumnAlias("ab_ume")
    private String abUme;

    @ColumnAlias("ab_cor")
    private Integer abCor;

    @ColumnAlias("ab_emss")
    private String abEmss;

    @ColumnAlias("ab_puon")
    private String abPuon;

    @ColumnAlias("ab_rfus")
    private Integer abRfus;

    @ColumnAlias("ab_ron")
    private String abRon;

    @ColumnAlias("ab_name")
    private String abName;

    @ColumnAlias("ab_mobile_phone")
    private String abMobilePhone;

    @ColumnAlias("ab_password")
    private String abPassword;

    @ColumnAlias("ab_position")
    private String abPosition;

    @ColumnAlias("status")
    private String status;

    public Integer getAbIdil() {
        return this.abIdil;
    }

    public void setAbIdil(Integer abIdil) {
        this.abIdil = abIdil;
    }

    public String getAbCoorsa() {
        return this.abCoorsa;
    }

    public void setAbCoorsa(String abCoorsa) {
        this.abCoorsa = abCoorsa;
    }

    public String getAbUme() {
        return this.abUme;
    }

    public void setAbUme(String abUme) {
        this.abUme = abUme;
    }

    public Integer getAbCor() {
        return this.abCor;
    }

    public void setAbCor(Integer abCor) {
        this.abCor = abCor;
    }

    public String getAbEmss() {
        return this.abEmss;
    }

    public void setAbEmss(String abEmss) {
        this.abEmss = abEmss;
    }

    public String getAbPuon() {
        return this.abPuon;
    }

    public void setAbPuon(String abPuon) {
        this.abPuon = abPuon;
    }

    public Integer getAbRfus() {
        return this.abRfus;
    }

    public void setAbRfus(Integer abRfus) {
        this.abRfus = abRfus;
    }

    public String getAbRon() {
        return this.abRon;
    }

    public void setAbRon(String abRon) {
        this.abRon = abRon;
    }

    public String getAbName() {
        return this.abName;
    }

    public void setAbName(String abName) {
        this.abName = abName;
    }

    public String getAbMobilePhone() {
        return this.abMobilePhone;
    }

    public void setAbMobilePhone(String abMobilePhone) {
        this.abMobilePhone = abMobilePhone;
    }

    public String getAbPassword() {
        return this.abPassword;
    }

    public void setAbPassword(String abPassword) {
        this.abPassword = abPassword;
    }

    public String getAbPosition() {
        return this.abPosition;
    }

    public void setAbPosition(String abPosition) {
        this.abPosition = abPosition;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetPicResponse)) return false;
        final GetPicResponse getPicResponse = (GetPicResponse) o;
        return Objects.equals(getAbIdil(), getPicResponse.getAbIdil()) &&
                Objects.equals(getAbCoorsa(), getPicResponse.getAbCoorsa()) &&
                Objects.equals(getAbUme(), getPicResponse.getAbUme()) &&
                Objects.equals(getAbCor(), getPicResponse.getAbCor()) &&
                Objects.equals(getAbEmss(), getPicResponse.getAbEmss()) &&
                Objects.equals(getAbPuon(), getPicResponse.getAbPuon()) &&
                Objects.equals(getAbRfus(), getPicResponse.getAbRfus()) &&
                Objects.equals(getAbRon(), getPicResponse.getAbRon()) &&
                Objects.equals(getAbName(), getPicResponse.getAbName()) &&
                Objects.equals(getAbMobilePhone(), getPicResponse.getAbMobilePhone()) &&
                Objects.equals(getAbPassword(), getPicResponse.getAbPassword()) &&
                Objects.equals(getAbPosition(), getPicResponse.getAbPosition()) &&
                Objects.equals(getStatus(), getPicResponse.getStatus());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getAbIdil(),
                getAbCoorsa(),
                getAbUme(),
                getAbCor(),
                getAbEmss(),
                getAbPuon(),
                getAbRfus(),
                getAbRon(),
                getAbName(),
                getAbMobilePhone(),
                getAbPassword(),
                getAbPosition(),
                getStatus());
    }
}