/*Copyright (c) 2020-2021 aio.co.id All Rights Reserved.
 This software is the confidential and proprietary information of aio.co.id You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with aio.co.id*/
package id.co.aio.procure_to_pay.avm2.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;

public class QupdateExemptionFileRequest implements Serializable {


    @JsonProperty("fileName")
    @NotNull
    private String fileName;

    @JsonProperty("filePath")
    @NotNull
    private String filePath;

    @JsonProperty("idFileExemption")
    @NotNull
    private String idFileExemption;

    public String getFileName() {
        return this.fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getFilePath() {
        return this.filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    public String getIdFileExemption() {
        return this.idFileExemption;
    }

    public void setIdFileExemption(String idFileExemption) {
        this.idFileExemption = idFileExemption;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof QupdateExemptionFileRequest)) return false;
        final QupdateExemptionFileRequest qupdateExemptionFileRequest = (QupdateExemptionFileRequest) o;
        return Objects.equals(getFileName(), qupdateExemptionFileRequest.getFileName()) &&
                Objects.equals(getFilePath(), qupdateExemptionFileRequest.getFilePath()) &&
                Objects.equals(getIdFileExemption(), qupdateExemptionFileRequest.getIdFileExemption());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getFileName(),
                getFilePath(),
                getIdFileExemption());
    }
}