/*Copyright (c) 2020-2021 aio.co.id All Rights Reserved.
 This software is the confidential and proprietary information of aio.co.id You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with aio.co.id*/
package id.co.aio.procure_to_pay.aio_ptp.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetCheckerTasklistResponse implements Serializable {


    @ColumnAlias("num_row")
    private Long numRow;

    @ColumnAlias("pr_id")
    private Integer prId;

    @ColumnAlias("pr_modified_at")
    private LocalDateTime prModifiedAt;

    @ColumnAlias("pr_ref")
    private String prRef;

    @ColumnAlias("task_type")
    private String taskType;

    @ColumnAlias("pr_created_name")
    private String prCreatedName;

    public Long getNumRow() {
        return this.numRow;
    }

    public void setNumRow(Long numRow) {
        this.numRow = numRow;
    }

    public Integer getPrId() {
        return this.prId;
    }

    public void setPrId(Integer prId) {
        this.prId = prId;
    }

    public LocalDateTime getPrModifiedAt() {
        return this.prModifiedAt;
    }

    public void setPrModifiedAt(LocalDateTime prModifiedAt) {
        this.prModifiedAt = prModifiedAt;
    }

    public String getPrRef() {
        return this.prRef;
    }

    public void setPrRef(String prRef) {
        this.prRef = prRef;
    }

    public String getTaskType() {
        return this.taskType;
    }

    public void setTaskType(String taskType) {
        this.taskType = taskType;
    }

    public String getPrCreatedName() {
        return this.prCreatedName;
    }

    public void setPrCreatedName(String prCreatedName) {
        this.prCreatedName = prCreatedName;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetCheckerTasklistResponse)) return false;
        final GetCheckerTasklistResponse getCheckerTasklistResponse = (GetCheckerTasklistResponse) o;
        return Objects.equals(getNumRow(), getCheckerTasklistResponse.getNumRow()) &&
                Objects.equals(getPrId(), getCheckerTasklistResponse.getPrId()) &&
                Objects.equals(getPrModifiedAt(), getCheckerTasklistResponse.getPrModifiedAt()) &&
                Objects.equals(getPrRef(), getCheckerTasklistResponse.getPrRef()) &&
                Objects.equals(getTaskType(), getCheckerTasklistResponse.getTaskType()) &&
                Objects.equals(getPrCreatedName(), getCheckerTasklistResponse.getPrCreatedName());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getNumRow(),
                getPrId(),
                getPrModifiedAt(),
                getPrRef(),
                getTaskType(),
                getPrCreatedName());
    }
}