/*Copyright (c) 2020-2021 aio.co.id All Rights Reserved.
 This software is the confidential and proprietary information of aio.co.id You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with aio.co.id*/
package id.co.aio.procure_to_pay.aio_ptp.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class QDepartmentMapUserResponse implements Serializable {


    @ColumnAlias("department")
    private String department;

    @ColumnAlias("department_id")
    private Integer departmentId;

    public String getDepartment() {
        return this.department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

    public Integer getDepartmentId() {
        return this.departmentId;
    }

    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof QDepartmentMapUserResponse)) return false;
        final QDepartmentMapUserResponse qdepartmentMapUserResponse = (QDepartmentMapUserResponse) o;
        return Objects.equals(getDepartment(), qdepartmentMapUserResponse.getDepartment()) &&
                Objects.equals(getDepartmentId(), qdepartmentMapUserResponse.getDepartmentId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getDepartment(),
                getDepartmentId());
    }
}