/*Copyright (c) 2020-2021 aio.co.id All Rights Reserved.
 This software is the confidential and proprietary information of aio.co.id You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with aio.co.id*/
package id.co.aio.procure_to_pay.aio_ptp.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.sql.Date;
import java.time.LocalDateTime;
import java.util.Objects;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;

public class UpdateUserMapStatusRequest implements Serializable {


    @JsonProperty("status")
    @NotNull
    private String status;

    @JsonProperty("from_date")
    private Date fromDate;

    @JsonProperty("to_date")
    private Date toDate;

    @JsonProperty("role_id")
    @NotNull
    private String roleId;

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Date getFromDate() {
        return this.fromDate;
    }

    public void setFromDate(Date fromDate) {
        this.fromDate = fromDate;
    }

    public Date getToDate() {
        return this.toDate;
    }

    public void setToDate(Date toDate) {
        this.toDate = toDate;
    }

    public String getRoleId() {
        return this.roleId;
    }

    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof UpdateUserMapStatusRequest)) return false;
        final UpdateUserMapStatusRequest updateUserMapStatusRequest = (UpdateUserMapStatusRequest) o;
        return Objects.equals(getStatus(), updateUserMapStatusRequest.getStatus()) &&
                Objects.equals(getFromDate(), updateUserMapStatusRequest.getFromDate()) &&
                Objects.equals(getToDate(), updateUserMapStatusRequest.getToDate()) &&
                Objects.equals(getRoleId(), updateUserMapStatusRequest.getRoleId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getStatus(),
                getFromDate(),
                getToDate(),
                getRoleId());
    }
}