/*Copyright (c) 2020-2021 aio.co.id All Rights Reserved.
 This software is the confidential and proprietary information of aio.co.id You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with aio.co.id*/
package id.co.aio.procure_to_pay.sap_master;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * Cskt generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`CSKT`")
@IdClass(CsktId.class)
public class Cskt implements Serializable {

    private String kostl;
    private Date datbi;
    private String kokrs;
    private String ktext;
    private String ltext;
    private String mctxt;

    @Id
    @Column(name = "`KOSTL`", nullable = false, length = 10)
    public String getKostl() {
        return this.kostl;
    }

    public void setKostl(String kostl) {
        this.kostl = kostl;
    }

    @Id
    @Column(name = "`DATBI`", nullable = false)
    public Date getDatbi() {
        return this.datbi;
    }

    public void setDatbi(Date datbi) {
        this.datbi = datbi;
    }

    @Id
    @Column(name = "`KOKRS`", nullable = false, length = 4)
    public String getKokrs() {
        return this.kokrs;
    }

    public void setKokrs(String kokrs) {
        this.kokrs = kokrs;
    }

    @Column(name = "`KTEXT`", nullable = true, length = 20)
    public String getKtext() {
        return this.ktext;
    }

    public void setKtext(String ktext) {
        this.ktext = ktext;
    }

    @Column(name = "`LTEXT`", nullable = true, length = 40)
    public String getLtext() {
        return this.ltext;
    }

    public void setLtext(String ltext) {
        this.ltext = ltext;
    }

    @Column(name = "`MCTXT`", nullable = true, length = 20)
    public String getMctxt() {
        return this.mctxt;
    }

    public void setMctxt(String mctxt) {
        this.mctxt = mctxt;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Cskt)) return false;
        final Cskt cskt = (Cskt) o;
        return Objects.equals(getKostl(), cskt.getKostl()) &&
                Objects.equals(getDatbi(), cskt.getDatbi()) &&
                Objects.equals(getKokrs(), cskt.getKokrs());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getKostl(),
                getDatbi(),
                getKokrs());
    }
}