/*Copyright (c) 2020-2021 aio.co.id All Rights Reserved.
 This software is the confidential and proprietary information of aio.co.id You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with aio.co.id*/
package id.co.aio.procure_to_pay.sap_master;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * T052u generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`T052U`")
@IdClass(T052uId.class)
public class T052u implements Serializable {

    private Byte ztagg;
    private String zterm;
    private String text1;

    @Id
    @Column(name = "`ZTAGG`", nullable = false, scale = 0, precision = 2)
    public Byte getZtagg() {
        return this.ztagg;
    }

    public void setZtagg(Byte ztagg) {
        this.ztagg = ztagg;
    }

    @Id
    @Column(name = "`ZTERM`", nullable = false, length = 4)
    public String getZterm() {
        return this.zterm;
    }

    public void setZterm(String zterm) {
        this.zterm = zterm;
    }

    @Column(name = "`TEXT1`", nullable = true, length = 50)
    public String getText1() {
        return this.text1;
    }

    public void setText1(String text1) {
        this.text1 = text1;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof T052u)) return false;
        final T052u t052u = (T052u) o;
        return Objects.equals(getZtagg(), t052u.getZtagg()) &&
                Objects.equals(getZterm(), t052u.getZterm());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getZtagg(),
                getZterm());
    }
}