/*Copyright (c) 2020-2021 aio.co.id All Rights Reserved.
 This software is the confidential and proprietary information of aio.co.id You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with aio.co.id*/
package id.co.aio.procure_to_pay.sap_master;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * VPtpCostcenter generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`v_ptp_costcenter`")
@IdClass(VPtpCostcenterId.class)
public class VPtpCostcenter implements Serializable {

    private String costCenterCategory;
    private String shortText;
    private String werks;
    private String profitCenter;
    private String gsber;
    private String personResponsible;
    private Date validFromDate;
    private Date validToDate;
    private String controllingArea;
    private String longText;
    private String costCenter;
    private String companyCode;
    private String descOfMerchantId;

    @Id
    @Column(name = "`cost_center_category`", nullable = true, length = 1)
    public String getCostCenterCategory() {
        return this.costCenterCategory;
    }

    public void setCostCenterCategory(String costCenterCategory) {
        this.costCenterCategory = costCenterCategory;
    }

    @Id
    @Column(name = "`short_text`", nullable = true, length = 20)
    public String getShortText() {
        return this.shortText;
    }

    public void setShortText(String shortText) {
        this.shortText = shortText;
    }

    @Id
    @Column(name = "`WERKS`", nullable = true, length = 4)
    public String getWerks() {
        return this.werks;
    }

    public void setWerks(String werks) {
        this.werks = werks;
    }

    @Id
    @Column(name = "`profit_center`", nullable = true, length = 10)
    public String getProfitCenter() {
        return this.profitCenter;
    }

    public void setProfitCenter(String profitCenter) {
        this.profitCenter = profitCenter;
    }

    @Id
    @Column(name = "`GSBER`", nullable = true, length = 4)
    public String getGsber() {
        return this.gsber;
    }

    public void setGsber(String gsber) {
        this.gsber = gsber;
    }

    @Id
    @Column(name = "`person_responsible`", nullable = true, length = 20)
    public String getPersonResponsible() {
        return this.personResponsible;
    }

    public void setPersonResponsible(String personResponsible) {
        this.personResponsible = personResponsible;
    }

    @Id
    @Column(name = "`valid_from_date`", nullable = true)
    public Date getValidFromDate() {
        return this.validFromDate;
    }

    public void setValidFromDate(Date validFromDate) {
        this.validFromDate = validFromDate;
    }

    @Id
    @Column(name = "`valid_to_date`", nullable = false)
    public Date getValidToDate() {
        return this.validToDate;
    }

    public void setValidToDate(Date validToDate) {
        this.validToDate = validToDate;
    }

    @Id
    @Column(name = "`controlling_area`", nullable = false, length = 4)
    public String getControllingArea() {
        return this.controllingArea;
    }

    public void setControllingArea(String controllingArea) {
        this.controllingArea = controllingArea;
    }

    @Id
    @Column(name = "`long_text`", nullable = true, length = 40)
    public String getLongText() {
        return this.longText;
    }

    public void setLongText(String longText) {
        this.longText = longText;
    }

    @Id
    @Column(name = "`cost_center`", nullable = false, length = 10)
    public String getCostCenter() {
        return this.costCenter;
    }

    public void setCostCenter(String costCenter) {
        this.costCenter = costCenter;
    }

    @Id
    @Column(name = "`company_code`", nullable = true, length = 4)
    public String getCompanyCode() {
        return this.companyCode;
    }

    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode;
    }

    @Id
    @Column(name = "`desc_of_merchant_id`", nullable = true, length = 20)
    public String getDescOfMerchantId() {
        return this.descOfMerchantId;
    }

    public void setDescOfMerchantId(String descOfMerchantId) {
        this.descOfMerchantId = descOfMerchantId;
    }



    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof VPtpCostcenter)) return false;
        final VPtpCostcenter vptpCostcenter = (VPtpCostcenter) o;
        return Objects.equals(getCostCenterCategory(), vptpCostcenter.getCostCenterCategory()) &&
                Objects.equals(getShortText(), vptpCostcenter.getShortText()) &&
                Objects.equals(getWerks(), vptpCostcenter.getWerks()) &&
                Objects.equals(getProfitCenter(), vptpCostcenter.getProfitCenter()) &&
                Objects.equals(getGsber(), vptpCostcenter.getGsber()) &&
                Objects.equals(getPersonResponsible(), vptpCostcenter.getPersonResponsible()) &&
                Objects.equals(getValidFromDate(), vptpCostcenter.getValidFromDate()) &&
                Objects.equals(getValidToDate(), vptpCostcenter.getValidToDate()) &&
                Objects.equals(getControllingArea(), vptpCostcenter.getControllingArea()) &&
                Objects.equals(getLongText(), vptpCostcenter.getLongText()) &&
                Objects.equals(getCostCenter(), vptpCostcenter.getCostCenter()) &&
                Objects.equals(getCompanyCode(), vptpCostcenter.getCompanyCode()) &&
                Objects.equals(getDescOfMerchantId(), vptpCostcenter.getDescOfMerchantId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getCostCenterCategory(),
                getShortText(),
                getWerks(),
                getProfitCenter(),
                getGsber(),
                getPersonResponsible(),
                getValidFromDate(),
                getValidToDate(),
                getControllingArea(),
                getLongText(),
                getCostCenter(),
                getCompanyCode(),
                getDescOfMerchantId());
    }
}