/*Copyright (c) 2020-2021 aio.co.id All Rights Reserved.
 This software is the confidential and proprietary information of aio.co.id You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with aio.co.id*/
package id.co.aio.procure_to_pay.sap_master;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

public class VPtpMaterialGroupId implements Serializable {

    private String authGroup;
    private String materialGroupDesc60;
    private String materialGroup;
    private String materialGroupDesc;

    public String getAuthGroup() {
        return this.authGroup;
    }

    public void setAuthGroup(String authGroup) {
        this.authGroup = authGroup;
    }

    public String getMaterialGroupDesc60() {
        return this.materialGroupDesc60;
    }

    public void setMaterialGroupDesc60(String materialGroupDesc60) {
        this.materialGroupDesc60 = materialGroupDesc60;
    }

    public String getMaterialGroup() {
        return this.materialGroup;
    }

    public void setMaterialGroup(String materialGroup) {
        this.materialGroup = materialGroup;
    }

    public String getMaterialGroupDesc() {
        return this.materialGroupDesc;
    }

    public void setMaterialGroupDesc(String materialGroupDesc) {
        this.materialGroupDesc = materialGroupDesc;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof VPtpMaterialGroup)) return false;
        final VPtpMaterialGroup vptpMaterialGroup = (VPtpMaterialGroup) o;
        return Objects.equals(getAuthGroup(), vptpMaterialGroup.getAuthGroup()) &&
                Objects.equals(getMaterialGroupDesc60(), vptpMaterialGroup.getMaterialGroupDesc60()) &&
                Objects.equals(getMaterialGroup(), vptpMaterialGroup.getMaterialGroup()) &&
                Objects.equals(getMaterialGroupDesc(), vptpMaterialGroup.getMaterialGroupDesc());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getAuthGroup(),
                getMaterialGroupDesc60(),
                getMaterialGroup(),
                getMaterialGroupDesc());
    }
}